// src/routes/tidal/+page.svelte
<script lang="ts">
    import { enhance } from '$app/forms';
    import { resolve } from '$app/paths';
    import type { ActionData, PageData } from './$types';

    let { data, form }: { data: PageData; form: ActionData } = $props();
    let loading = $state(false);

    function tidalSearchUrl(playlistName: string): string {
        return `https://tidal.com/search?q=${encodeURIComponent(playlistName)}`;
    }
</script>

<svelte:head>
    <title>Tidal Playlist Suggestions – mijnnaamisbas</title>
</svelte:head>

<div class="page-container">
    <header class="page-header">
        <h1>🎵 Tidal Playlist Suggestions</h1>
        <p class="subtitle">Powered by Mistral AI — European AI</p>
    </header>

    <!-- Tidal Connection Status -->
    <section class="tidal-connection">
        {#if data.authenticated}
            <div class="connection-status connected">
                <div class="status-info">
                    <span class="status-icon">✓</span>
                    <div>
                        <strong>Connected to Tidal</strong>
                        {#if data.userTaste}
                            <p class="user-stats">
                                {data.userTaste.totalPlaylists} playlists · {data.userTaste.totalTracks} tracks
                                {#if data.userTaste.topGenres.length > 0}
                                    · {data.userTaste.topGenres.slice(0, 3).join(', ')}
                                {/if}
                            </p>
                        {/if}
                    </div>
                </div>
                <form method="POST" action="/tidal/logout">
                    <button type="submit" class="disconnect-btn">Disconnect</button>
                </form>
            </div>
            {#if data.justConnected}
                <div class="success-message">
                    🎉 Successfully connected! Your suggestions will now be personalized based on your Tidal library.
                </div>
            {/if}
        {:else}
            <div class="connection-status disconnected">
                <div class="connection-prompt">
                    <h3>Get Personalized Suggestions</h3>
                    <p>Connect your Tidal account to receive AI-powered playlist recommendations based on your actual music taste.</p>
                    <a href="/tidal/login" class="connect-btn">
                        <span>🎵</span> Connect Tidal Account
                    </a>
                </div>
            </div>
        {/if}

        {#if data.error}
            <div class="error-message">
                {#if data.error === 'auth_failed'}
                    Failed to authorize with Tidal. Please try again.
                {:else if data.error === 'login_failed'}
                    Failed to complete login. Please try again.
                {:else}
                    An error occurred. Please try again.
                {/if}
            </div>
        {/if}
    </section>

    <section class="suggestion-form">
        <h2>What are you in the mood for?</h2>
        <form
            method="POST"
            action="?/suggest"
            use:enhance={() => {
                loading = true;
                return async ({ update }) => {
                    await update();
                    loading = false;
                };
            }}
        >
            <div class="form-group">
                <label for="mood">Mood / Feeling</label>
                <input
                    id="mood"
                    name="mood"
                    type="text"
                    placeholder="e.g. relaxed, energetic, melancholic..."
                    class="form-input"
                    required
                />
            </div>
            <div class="form-group">
                <label for="genre">Genre (optional)</label>
                <input
                    id="genre"
                    name="genre"
                    type="text"
                    placeholder="e.g. jazz, electronic, indie..."
                    class="form-input"
                />
            </div>
            <button type="submit" class="submit-btn" disabled={loading}>
                {loading ? 'Generating...' : '✨ Get Suggestions'}
            </button>
        </form>
    </section>

    {#if form?.error}
        <div class="error-message">{form.error}</div>
    {/if}

    {#if form?.suggestions && form.suggestions.length > 0}
        <section class="suggestions">
            <div class="suggestions-header">
                <h2>Your Playlist Suggestions</h2>
                {#if form.personalized}
                    <span class="personalized-badge">✨ Personalized for you</span>
                {/if}
            </div>
            <div class="playlist-grid">
                {#each form.suggestions as playlist (playlist.name)}
                    <div class="playlist-card">
                        <h3 class="playlist-name">{playlist.name}</h3>
                        <p class="playlist-description">{playlist.description}</p>
                        {#if playlist.artists && playlist.artists.length > 0}
                            <div class="artists">
                                <span class="artists-label">Featured artists:</span>
                                <ul class="artists-list">
                                    {#each playlist.artists as artist, index (index)}
                                        <li>{artist}</li>
                                    {/each}
                                </ul>
                            </div>
                        {/if}
                        <a
                            href={tidalSearchUrl(playlist.name)}
                            target="_blank"
                            rel="noopener noreferrer"
                            class="tidal-link"
                            data-sveltekit-reload
                        >
                            Search on Tidal
                        </a>
                    </div>
                {/each}
            </div>
        </section>
    {/if}
</div>

<style>
.page-container {
    max-width: 1000px;
    margin: 0 auto;
    padding: 2rem;
}

.page-header {
    margin-bottom: 2rem;
}

.page-header h1 {
    font-size: var(--font-size-4xl);
    color: var(--color-text-primary);
    margin: 0 0 var(--space-sm) 0;
}

.subtitle {
    color: var(--color-text-secondary);
    font-size: var(--font-size-sm);
    margin: 0;
}

/* Tidal Connection Status */
.tidal-connection {
    margin-bottom: 2rem;
}

.connection-status {
    background: var(--color-bg-primary);
    border-radius: var(--radius-lg);
    border: var(--border-width-thick) solid var(--color-border-primary);
    padding: var(--space-lg);
}

.connection-status.connected {
    border-color: var(--color-primary);
    background: var(--color-primary-light);
}

.connection-status.connected .status-info {
    display: flex;
    align-items: flex-start;
    gap: 1rem;
    flex: 1;
}

.connection-status.connected .status-icon {
    background: var(--gradient-primary);
    border-radius: var(--radius-full);
    color: var(--color-text-inverse);
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: var(--font-weight-bold);
    height: 28px;
    width: 28px;
    flex-shrink: 0;
}

.connection-status.connected strong {
    color: var(--color-text-primary);
    display: block;
    margin-bottom: var(--space-xs);
}

.user-stats {
    color: var(--color-text-secondary);
    font-size: var(--font-size-sm);
    margin: 0;
}

.connection-status.connected form {
    margin-top: 1rem;
}

.disconnect-btn {
    background: transparent;
    border: var(--border-width) solid var(--color-border-primary);
    border-radius: var(--radius-sm);
    color: var(--color-text-secondary);
    cursor: pointer;
    font-size: var(--font-size-sm);
    padding: var(--space-sm) var(--space-md);
    transition: all var(--transition-fast);
}

.disconnect-btn:hover {
    background: var(--color-bg-secondary);
    border-color: var(--color-text-tertiary);
}

.connection-status.disconnected {
    border-color: var(--color-border-primary);
}

.connection-prompt {
    text-align: center;
}

.connection-prompt h3 {
    color: var(--color-text-primary);
    font-size: var(--font-size-xl);
    margin: 0 0 var(--space-sm);
}

.connection-prompt p {
    color: var(--color-text-secondary);
    margin: 0 0 var(--space-lg);
}

.connect-btn {
    background: var(--gradient-primary);
    border-radius: var(--radius-sm);
    color: var(--color-text-inverse);
    display: inline-flex;
    align-items: center;
    gap: var(--space-sm);
    font-weight: var(--font-weight-semibold);
    padding: var(--space-md) var(--space-lg);
    text-decoration: none;
    transition: transform var(--transition-fast), box-shadow var(--transition-fast);
}

.connect-btn:hover {
    transform: translateY(-2px);
    box-shadow: var(--shadow-md);
}

.connect-btn span {
    font-size: 1.25rem;
}

.success-message {
    background: var(--color-primary-light);
    border: var(--border-width) solid var(--color-primary);
    border-radius: var(--radius-sm);
    color: var(--color-primary-dark);
    margin-top: var(--space-md);
    padding: var(--space-md);
}

.suggestion-form {
    background: var(--color-bg-primary);
    border-radius: var(--radius-lg);
    border: var(--border-width) solid var(--color-border-primary);
    padding: var(--space-xl);
    margin-bottom: var(--space-xl);
}

.suggestion-form h2 {
    color: var(--color-text-primary);
    font-size: var(--font-size-xl);
    margin: 0 0 var(--space-lg);
}

.form-group {
    margin-bottom: 1.5rem;
}

.form-group label {
    display: block;
    font-weight: var(--font-weight-semibold);
    margin-bottom: var(--space-sm);
    color: var(--color-text-primary);
}

.form-input {
    width: 100%;
    padding: var(--space-md) var(--space-md);
    border: var(--border-width) solid var(--color-border-primary);
    border-radius: var(--radius-sm);
    font-size: var(--font-size-base);
    transition: border-color var(--transition-fast);
    box-sizing: border-box;
}

.form-input:focus {
    outline: none;
    border-color: var(--color-border-focus);
    box-shadow: var(--shadow-focus);
}

.submit-btn {
    background: var(--gradient-primary);
    border: none;
    border-radius: var(--radius-sm);
    color: var(--color-text-inverse);
    cursor: pointer;
    font-size: var(--font-size-base);
    font-weight: var(--font-weight-semibold);
    padding: var(--space-md) var(--space-xl);
    transition: transform var(--transition-fast), box-shadow var(--transition-fast);
}

.submit-btn:hover {
    transform: translateY(-2px);
    box-shadow: var(--shadow-md);
}

.submit-btn:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: var(--shadow-md);
}

.submit-btn:disabled {
    cursor: not-allowed;
    opacity: 0.6;
}

.error-message {
    background: var(--color-error-light);
    border: 1px solid var(--color-error);
    border-radius: 4px;
    color: var(--color-error);
    margin-bottom: 2rem;
    padding: 1rem;
}

.suggestions {
    margin-top: 2rem;
}

.suggestions-header {
    display: flex;
    align-items: center;
    gap: 1rem;
    margin-bottom: 1.5rem;
}

.suggestions-header h2 {
    margin: 0;
}

.personalized-badge {
    background: var(--gradient-primary);
    border-radius: 16px;
    color: var(--color-text-inverse);
    font-size: 0.75rem;
    font-weight: 600;
    padding: 0.25rem 0.75rem;
}

.suggestions h2 {
    margin-bottom: 1.5rem;
}

.playlist-grid {
    display: grid;
    gap: 1.5rem;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
}

.playlist-card {
    background: var(--color-surface);
    border: 1px solid var(--color-border-primary);
    border-radius: 8px;
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
    padding: 1.5rem;
    transition: transform 0.2s, box-shadow 0.2s;
}

.playlist-card:hover {
    transform: translateY(-2px);
    box-shadow: var(--shadow-md);
}

.playlist-name {
    color: var(--color-text-primary);
    font-size: 1.1rem;
    margin: 0;
}

.playlist-description {
    color: var(--color-text-secondary);
    font-size: 0.9rem;
    margin: 0;
}

.artists {
    font-size: 0.875rem;
}

.artists-label {
    color: var(--color-text-secondary);
    font-weight: 600;
}

.artists-list {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    list-style: none;
    margin: 0.5rem 0 0;
    padding: 0;
}

.artists-list li {
    background: var(--color-background-secondary);
    border-radius: 4px;
    padding: 0.2rem 0.5rem;
}

.tidal-link {
    background: var(--color-text-primary);
    border-radius: 4px;
    color: var(--color-text-inverse);
    display: inline-block;
    font-weight: 600;
    margin-top: auto;
    padding: 0.5rem 1rem;
    text-align: center;
    text-decoration: none;
    transition: transform 0.2s, box-shadow 0.2s;
}

.tidal-link:hover {
    transform: translateY(-2px);
    box-shadow: var(--shadow-md);
}
</style>

// pages/tidal.vue
<template>
    <div class="tidal">
        <div class="tidal__header">
            <h1 class="tidal__title">
                Tidal Playlist Suggestions
            </h1>
            <p class="tidal__subtitle">
                Connect your Tidal account and get AI-powered playlist suggestions based on your taste.
            </p>
        </div>

        <!-- Error message -->
        <div
            v-if="error"
            class="tidal__error"
        >
            {{ error }}
        </div>

        <!-- Step 1: Connect to Tidal -->
        <section
            v-if="!connected"
            class="tidal__section"
        >
            <h2 class="tidal__section-title">
                Step 1: Connect to Tidal
            </h2>
            <p>
                Authorise this app to read your Tidal playlists.
                You will be redirected to Tidal's login page.
            </p>
            <button
                class="tidal__button tidal__button--primary"
                :disabled="!tidalClientId"
                @click="connectTidal"
            >
                Connect with Tidal
            </button>
            <p
                v-if="!tidalClientId"
                class="tidal__hint"
            >
                Set <code>TIDAL_CLIENT_ID</code> in your environment to enable Tidal login.
            </p>
        </section>

        <!-- Connected state -->
        <template v-else>
            <div class="tidal__connected-bar">
                <span>Connected as <strong>{{ userFirstName }}</strong></span>
                <button
                    class="tidal__button tidal__button--secondary"
                    @click="disconnect"
                >
                    Disconnect
                </button>
            </div>

            <!-- Step 2: Load Playlists -->
            <section class="tidal__section">
                <h2 class="tidal__section-title">
                    Step 2: Your Playlists
                </h2>

                <button
                    class="tidal__button tidal__button--primary"
                    :disabled="loadingPlaylists"
                    @click="loadPlaylists"
                >
                    {{ loadingPlaylists ? 'Loading…' : 'Load playlists' }}
                </button>

                <ul
                    v-if="playlists.length"
                    class="tidal__playlist-list"
                >
                    <li
                        v-for="playlist in playlists"
                        :key="playlist.uuid"
                        class="tidal__playlist-item"
                        :class="{ 'tidal__playlist-item--selected': selectedPlaylistIds.includes(playlist.uuid) }"
                        @click="togglePlaylist(playlist.uuid)"
                    >
                        <span class="tidal__playlist-name">{{ playlist.title }}</span>
                        <span class="tidal__playlist-count">{{ playlist.numberOfTracks }} tracks</span>
                    </li>
                </ul>

                <div
                    v-if="playlists.length && !tracksLoaded"
                    class="tidal__load-tracks"
                >
                    <button
                        class="tidal__button tidal__button--secondary"
                        :disabled="loadingTracks || !selectedPlaylistIds.length"
                        @click="loadSelectedTracks"
                    >
                        {{ loadingTracks ? 'Loading tracks…' : 'Load tracks from selected playlists' }}
                    </button>
                    <p
                        v-if="!selectedPlaylistIds.length"
                        class="tidal__hint"
                    >
                        Select one or more playlists above.
                    </p>
                </div>

                <div
                    v-if="topArtists.length"
                    class="tidal__taste-profile"
                >
                    <h3 class="tidal__section-subtitle">
                        Your taste profile
                    </h3>
                    <p class="tidal__hint">
                        Based on {{ tracks.length }} tracks across your selected playlists.
                    </p>
                    <ul class="tidal__artist-list">
                        <li
                            v-for="artist in topArtists"
                            :key="artist.name"
                            class="tidal__artist-item"
                        >
                            <span class="tidal__artist-name">{{ artist.name }}</span>
                            <span class="tidal__artist-count">{{ artist.count }}×</span>
                        </li>
                    </ul>
                </div>
            </section>

            <!-- Step 3: Get Suggestions -->
            <section
                v-if="tracksLoaded"
                class="tidal__section"
            >
                <h2 class="tidal__section-title">
                    Step 3: Get Suggestions
                </h2>
                <p>
                    Describe the playlist you want — for example
                    <em>"post hardcore bands"</em>, <em>"chill lo-fi for studying"</em>, or
                    <em>"90s alternative rock"</em>.
                </p>

                <div class="tidal__prompt-row">
                    <input
                        v-model="prompt"
                        class="tidal__prompt-input"
                        type="text"
                        placeholder="e.g. post hardcore bands"
                        @keyup.enter="getSuggestions"
                    >
                    <button
                        class="tidal__button tidal__button--primary"
                        :disabled="loadingSuggestions || !prompt.trim()"
                        @click="getSuggestions"
                    >
                        {{ loadingSuggestions ? 'Thinking…' : 'Suggest' }}
                    </button>
                </div>
            </section>

            <!-- Suggestions result -->
            <section
                v-if="suggestions"
                class="tidal__section tidal__suggestions"
            >
                <h2 class="tidal__suggestions-name">
                    {{ suggestions.name }}
                </h2>
                <p class="tidal__suggestions-description">
                    {{ suggestions.description }}
                </p>
                <p class="tidal__suggestions-reasoning">
                    <em>{{ suggestions.reasoning }}</em>
                </p>

                <ol class="tidal__track-list">
                    <li
                        v-for="(track, index) in suggestions.tracks"
                        :key="index"
                        class="tidal__track-item"
                    >
                        <span class="tidal__track-number">{{ index + 1 }}.</span>
                        <div class="tidal__track-info">
                            <span class="tidal__track-title">{{ track.title }}</span>
                            <span class="tidal__track-artist">{{ track.artist }}</span>
                            <span
                                v-if="track.album"
                                class="tidal__track-album"
                            >{{ track.album }}</span>
                            <span
                                v-if="track.reason"
                                class="tidal__track-reason"
                            >{{ track.reason }}</span>
                        </div>
                    </li>
                </ol>
            </section>
        </template>
    </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { mapState, mapGetters } from 'vuex'

const PKCE_VERIFIER_KEY = 'tidal_pkce_verifier'
const TIDAL_AUTH_URL = 'https://login.tidal.com/oauth2/authorize'

async function generatePKCE(): Promise<{ verifier: string; challenge: string }> {
    const array = new Uint8Array(64)
    crypto.getRandomValues(array)
    const verifier = btoa(String.fromCharCode(...array))
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=/g, '')

    const encoded = new TextEncoder().encode(verifier)
    const hashBuffer = await crypto.subtle.digest('SHA-256', encoded)
    const hashArray = new Uint8Array(hashBuffer)
    const challenge = btoa(String.fromCharCode(...hashArray))
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=/g, '')

    return { verifier, challenge }
}

export default Vue.extend({
    name: 'TidalPage',

    data() {
        return {
            prompt: '',
            selectedPlaylistIds: [] as string[],
        }
    },

    computed: {
        ...mapState('tidal', [
            'connected',
            'userFirstName',
            'playlists',
            'tracks',
            'suggestions',
            'loadingPlaylists',
            'loadingTracks',
            'loadingSuggestions',
            'error',
        ]),
        ...mapGetters('tidal', ['topArtists']),

        tidalClientId(): string {
            return (this.$config as { tidalClientId?: string }).tidalClientId || ''
        },

        tidalRedirectUri(): string {
            if (process.client) {
                return `${window.location.origin}/tidal`
            }
            return ''
        },

        tracksLoaded(): boolean {
            return this.tracks.length > 0
        },
    },

    async mounted() {
        // Handle OAuth callback — check for ?code= in URL
        if (process.client) {
            const params = new URLSearchParams(window.location.search)
            const code = params.get('code')

            if (code) {
                const codeVerifier = sessionStorage.getItem(PKCE_VERIFIER_KEY)
                sessionStorage.removeItem(PKCE_VERIFIER_KEY)

                if (codeVerifier) {
                    try {
                        await this.$store.dispatch('tidal/exchangeToken', {
                            code,
                            codeVerifier,
                            redirectUri: this.tidalRedirectUri,
                        })
                        // Clean the URL after successful exchange
                        window.history.replaceState({}, document.title, '/tidal')
                    } catch {
                        // Error is already stored in the Vuex state
                    }
                }
            }
        }
    },

    methods: {
        async connectTidal() {
            const { verifier, challenge } = await generatePKCE()
            sessionStorage.setItem(PKCE_VERIFIER_KEY, verifier)

            const params = new URLSearchParams({
                response_type: 'code',
                client_id: this.tidalClientId,
                redirect_uri: this.tidalRedirectUri,
                scope: 'r_usr',
                code_challenge: challenge,
                code_challenge_method: 'S256',
            })

            window.location.href = `${TIDAL_AUTH_URL}?${params}`
        },

        disconnect() {
            this.$store.commit('tidal/reset')
        },

        async loadPlaylists() {
            await this.$store.dispatch('tidal/fetchPlaylists')
        },

        togglePlaylist(id: string) {
            const index = this.selectedPlaylistIds.indexOf(id)
            if (index === -1) {
                this.selectedPlaylistIds.push(id)
            } else {
                this.selectedPlaylistIds.splice(index, 1)
            }
        },

        async loadSelectedTracks() {
            for (const id of this.selectedPlaylistIds) {
                await this.$store.dispatch('tidal/fetchTracksForPlaylist', id)
            }
        },

        async getSuggestions() {
            if (!this.prompt.trim()) return
            await this.$store.dispatch('tidal/getSuggestions', this.prompt.trim())
        },
    },
})
</script>

<style>
.tidal {
    max-width: 800px;
    margin: 0 auto;
    padding: 2rem;
}

.tidal__header {
    margin-bottom: 2rem;
}

.tidal__title {
    font-size: 2rem;
    font-weight: 700;
    margin-bottom: 0.5rem;
}

.tidal__subtitle {
    color: #666;
}

.tidal__error {
    background: #fee2e2;
    color: #b91c1c;
    padding: 1rem;
    border-radius: 0.5rem;
    margin-bottom: 1.5rem;
}

.tidal__section {
    margin-bottom: 2.5rem;
}

.tidal__section-title {
    font-size: 1.25rem;
    font-weight: 600;
    margin-bottom: 1rem;
}

.tidal__section-subtitle {
    font-size: 1rem;
    font-weight: 600;
    margin-bottom: 0.5rem;
}

.tidal__hint {
    font-size: 0.875rem;
    color: #888;
    margin-top: 0.5rem;
}

.tidal__button {
    display: inline-block;
    padding: 0.625rem 1.25rem;
    border: none;
    border-radius: 0.375rem;
    font-size: 1rem;
    cursor: pointer;
    transition: opacity 0.15s;
}

.tidal__button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
}

.tidal__button--primary {
    background: #1db954;
    color: #fff;
}

.tidal__button--primary:hover:not(:disabled) {
    opacity: 0.85;
}

.tidal__button--secondary {
    background: #e5e7eb;
    color: #374151;
}

.tidal__button--secondary:hover:not(:disabled) {
    background: #d1d5db;
}

.tidal__connected-bar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    background: #f0fdf4;
    border: 1px solid #bbf7d0;
    padding: 0.75rem 1rem;
    border-radius: 0.5rem;
    margin-bottom: 2rem;
}

.tidal__playlist-list {
    list-style: none;
    padding: 0;
    margin: 1rem 0;
    display: grid;
    gap: 0.5rem;
}

.tidal__playlist-item {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.75rem 1rem;
    border: 1px solid #e5e7eb;
    border-radius: 0.375rem;
    cursor: pointer;
    transition: background 0.1s;
}

.tidal__playlist-item:hover {
    background: #f9fafb;
}

.tidal__playlist-item--selected {
    border-color: #1db954;
    background: #f0fdf4;
}

.tidal__playlist-name {
    font-weight: 500;
}

.tidal__playlist-count {
    font-size: 0.875rem;
    color: #6b7280;
}

.tidal__load-tracks {
    margin-top: 1rem;
}

.tidal__taste-profile {
    margin-top: 1.5rem;
    padding: 1rem;
    background: #f9fafb;
    border-radius: 0.5rem;
}

.tidal__artist-list {
    list-style: none;
    padding: 0;
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
    margin-top: 0.5rem;
}

.tidal__artist-item {
    display: flex;
    align-items: center;
    gap: 0.25rem;
    background: #fff;
    border: 1px solid #e5e7eb;
    padding: 0.25rem 0.625rem;
    border-radius: 999px;
    font-size: 0.875rem;
}

.tidal__artist-count {
    color: #6b7280;
    font-size: 0.75rem;
}

.tidal__prompt-row {
    display: flex;
    gap: 0.75rem;
    margin-top: 1rem;
}

.tidal__prompt-input {
    flex: 1;
    padding: 0.625rem 0.875rem;
    border: 1px solid #d1d5db;
    border-radius: 0.375rem;
    font-size: 1rem;
    outline: none;
}

.tidal__prompt-input:focus {
    border-color: #1db954;
    box-shadow: 0 0 0 2px rgba(29, 185, 84, 0.2);
}

.tidal__suggestions {
    padding: 1.5rem;
    background: #f9fafb;
    border-radius: 0.75rem;
    border: 1px solid #e5e7eb;
}

.tidal__suggestions-name {
    font-size: 1.5rem;
    font-weight: 700;
    margin-bottom: 0.5rem;
}

.tidal__suggestions-description {
    color: #374151;
    margin-bottom: 0.5rem;
}

.tidal__suggestions-reasoning {
    color: #6b7280;
    font-size: 0.875rem;
    margin-bottom: 1.5rem;
}

.tidal__track-list {
    list-style: none;
    padding: 0;
    display: grid;
    gap: 0.75rem;
}

.tidal__track-item {
    display: flex;
    gap: 1rem;
    padding: 0.75rem;
    background: #fff;
    border-radius: 0.5rem;
    border: 1px solid #e5e7eb;
}

.tidal__track-number {
    color: #9ca3af;
    min-width: 1.5rem;
    font-variant-numeric: tabular-nums;
}

.tidal__track-info {
    display: flex;
    flex-direction: column;
    gap: 0.125rem;
}

.tidal__track-title {
    font-weight: 600;
}

.tidal__track-artist {
    color: #374151;
    font-size: 0.875rem;
}

.tidal__track-album {
    color: #6b7280;
    font-size: 0.8125rem;
}

.tidal__track-reason {
    color: #9ca3af;
    font-size: 0.75rem;
    font-style: italic;
    margin-top: 0.25rem;
}
</style>
